# Generated by Django 3.2.6 on 2021-08-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bothandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bot_id', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
