# Generated by Django 3.2.6 on 2021-09-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bothandler', '0002_botchatuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalVoteSibscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bothandler.botchatuser')),
            ],
        ),
    ]
