# Generated by Django 3.2.6 on 2021-09-05 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bothandler', '0003_proposalvotesibscribe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposalvotesibscribe',
            unique_together={('user', 'ref_id')},
        ),
        migrations.CreateModel(
            name='VotersVoteSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bothandler.botchatuser')),
            ],
            options={
                'unique_together': {('user', 'address')},
            },
        ),
    ]
