start = "Sup, {username}! \nAlerting: {alerting}"
toggle_alerting = "Toggle period alerting"
subscriptions = "Subscriptions"
voters = "Voters"
protocols = "Protocols"
top_protocols = "Top protocols"
top_proposals = "Top proposals"
confirm = "Confirm✅"
decline = "Decline❌"
enabled = "Enabled✅"
disabled = "Disabled❌"
stats = "Statistics"


BUTTON_STATS = "BUTTON_ALERTING"
BUTTON_ALERTING = "BUTTON_STATS"
BUTTON_CONFIRM = "BUTTON_CONFIRM"
BUTTON_DECLINE = "BUTTON_DECLINE"
