# Generated by Django 3.2.6 on 2021-09-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, unique=True)),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('alerting', models.BooleanField(default=False)),
                ('is_blocked_bot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=2000)),
                ('proposal_title', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botchatuser')),
            ],
            options={
                'unique_together': {('user', 'ref_id')},
            },
        ),
    ]
